export enum Config {
  ServerPort = "server_port",
  MongoUri = "mongo_uri",
  Neo4jUri = "neo4j_uri",
  Neo4jUser = "neo4j_user",
  Neo4jPassword = "neo4j_password",
  RedisUrl = "redis_url",
  OpenrouterApiKey = "openrouter_api_key",
  OpenrouterModel = "openrouter_model",
  ConcurrencyPdf = "concurrency.pdf",
  ConcurrencyWebsite = "concurrency.website",
  ConcurrencyGithub = "concurrency.github",
  ConcurrencyBitbucket = "concurrency.bitbucket",
  LogLevel = "log_level",
  LogRetentionDays = "log_retention_days",
}
